### ISSUE TITLE
Merge latest code from the CICE Consortium? 

### ISSUE THREAD

**Issue by aekiss** [OceansAus/cice5#11]
It looks like we last synched with the CICE consortium when 5.1.2 was merged in on Jun 24, 2015.

There have been a few commits to CICE5.1 since then (including bug fixes) - is it time to merge these in?
https://github.com/CICE-Consortium/CICE-svn-trunk/commits/master

**Comment by nichannah** [comment]
Our repository is now up to date with https://github.com/CICE-Consortium/CICE-svn-trunk/commits/master changes up to 28 April, 2018.
