### ISSUE TITLE
All non-master error output going to a single file and being overwritten

### ISSUE THREAD

**Issue by nicjhan** [OceansAus/cice5#4]
We seem to be losing error messages in CICE. At the moment we're guessing that it's because we have all (non-master) error output going to a single file. The error messages coming from one PE are being overwritten by info/debug output coming from others. 

This issue should fix the code so that error messages are sent to stderr. 

An alternative is to have individual output files for each PE however this has down-sides like too many files and it being difficult to find the one that has the relevant error message.

**Comment by aekiss** [comment]
relevant Slack discussion: https://arccss.slack.com/archives/C6PP0GU9Y/p1515844744000064
