### ISSUE TITLE
restart and input directories are the same

### ISSUE THREAD

**Issue by aidanheerdegen** [OceansAus/cice5#5]
The information model for MOM (and I think other models) is for inputs to be read from one directory, outputs to be saved to different directory, and restarts to be saved into another unique directory. In this way the contents of the restart directory can be copied/linked to the input directory for the next run.

Currently sicemass, u_star and the coupling fields are read from `restart_dir`

https://github.com/OceansAus/cice5/blob/fe7300227107bde802a217ff0d6ef7f92a6eb6c2/drivers/auscom/CICE_RunMod.F90#L106
https://github.com/OceansAus/cice5/blob/05597824ac633a1c6ce444ac78b651f3844092e1/drivers/auscom/CICE_InitMod.F90#L170

and written to `restart_dir`

https://github.com/OceansAus/cice5/blob/fe7300227107bde802a217ff0d6ef7f92a6eb6c2/drivers/auscom/CICE_RunMod.F90#L228

This can cause issues if these files are symbolic links then writing to them will overwrite the previous version of the restart file.

I would like to have separate INPUT and RESTART directories. 

Thoughts @nicjhan @aekiss @marshallward

**Comment by marshallward** [comment]
I think we've already talked about this, but just in case.. this is suggesting that CICE5 be modified to have INPUT and RESTART just like MOM.  Is that right?

Is this still something you'd like to do?

My feeling is that I'd rather support something as close to stock CICE as possible, and accommodate this version, rather than make CICE5 into something MOM-like.

**Comment by aidanheerdegen** [comment]
It isn't CICE we’re changing, but the AUSCOM driver code. In any case I’m testing a modified AUSCOM driver that is backwards compatible. When I’m satisfied it works without breaking old configs I’ll do a pull request so you can take a look

**Comment by marshallward** [comment]
That all sounds good to me.

**Comment by aidanheerdegen** [comment]
I lied. I did change CICE, but it is backwards compatible and doesn't break anything AFAICT.
