### ISSUE TITLE
abort_ice does not pass an error code to MPI_abort

### ISSUE THREAD

**Issue by aidanheerdegen** [OceansAus/cice5#8]
This is the same issue Martin Dix discovered:

https://accessdev.nci.org.au/trac/ticket/318

The call signature for `MPI_Abort` is
https://www.open-mpi.org/doc/v1.10/man3/MPI_Abort.3.php
```
MPI_ABORT(COMM, ERRORCODE, IERROR)            
    INTEGER        COMM, ERRORCODE, IERROR
comm
Communicator of tasks to abort.
errorcode
Error code to return to invoking environment.
```
It is called here:
https://github.com/OceansAus/cice5/blob/master/mpi/ice_exit.F90#L61
but the value of `ierr` is not set in the routine, so it is whatever it was initialised to by the compiler.

They had a similar issue with oasis_abort:

https://portal.enes.org/oasis/faq-forum/oasis3-forum/real-coupled-models/548853210

Apparently they decided oasis_abort should default to a non-zero value, it is an abort call after all.

**Comment by aidanheerdegen** [comment]
Any objections to this being merged? @nicjhan @aekiss @marshallward

**Comment by marshallward** [comment]
BTW how was this even able to build with two arguments?  Isn't `MPI_Abort` a three-argument function?

**Comment by aidanheerdegen** [comment]
Yes it is and I don't know

**Comment by aidanheerdegen** [comment]
As you can imagine @marshallward, this was rather confusing to `payu`. I have a related issue over on the oasis repo

https://github.com/OceansAus/oasis3-mct/issues/2

**Comment by russfiedler** [comment]
It compiles because it includes mpif.h rather than using the mpi module.



________________________________

**Comment by nicjhan** [comment]
Merged.
